In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
import json
import os
from pandas.io.json import json_normalize
pd.set_option('display.max_columns', 50)

In [2]:
path = "D:\\Dropbox\\Projeto Brasileirao\\caRtola\\data\\2015\\raw\\CartolaFC 2015 - Rodada 38 - 2015-12-11\\38\\"
files = os.listdir(path)

In [3]:
data = []
for file in files:
    f = path+file    
    with open(f) as data_file:    
        data.append(json.load(data_file))

In [4]:
for x in data[0]:
    print(x)

rodada_id
page
atleta

# Processamento

In [5]:
def prepara_scouts(loaded_json):
    aux = {}
    for i in loaded_json['atleta']:
        for j in i['scout']:
            aux.update({j['nome']:j['quantidade']})
        i['scout'] = aux
        aux = {}
    return loaded_json

In [6]:
for load in data:
    prepara_scouts(load)

In [7]:
rodada_38 = pd.DataFrame()
for file in data:
    rodada_38 = rodada_38.append(json_normalize(file['atleta']), ignore_index=True)

In [8]:
rodada_38.shape

(835, 47)

In [9]:
rodada_38.duplicated().value_counts()

False    823
True      12
dtype: int64

In [10]:
rodada_38.drop_duplicates(inplace=True)

In [11]:
rodada_38.columns

Index(['apelido', 'clube.abreviacao', 'clube.id', 'clube.mercado',
       'clube.nome', 'clube.slug', 'foto', 'id', 'jogos', 'media',
       'partida_clube_casa.abreviacao', 'partida_clube_casa.id',
       'partida_clube_casa.mercado', 'partida_clube_casa.nome',
       'partida_clube_casa.slug', 'partida_clube_visitante.abreviacao',
       'partida_clube_visitante.id', 'partida_clube_visitante.mercado',
       'partida_clube_visitante.nome', 'partida_clube_visitante.slug',
       'partida_data', 'pontos', 'posicao.abreviacao', 'posicao.id',
       'posicao.nome', 'preco', 'scout.A', 'scout.CA', 'scout.CV', 'scout.DD',
       'scout.DP', 'scout.FC', 'scout.FD', 'scout.FF', 'scout.FS', 'scout.FT',
       'scout.G', 'scout.GC', 'scout.GS', 'scout.I', 'scout.PE', 'scout.PP',
       'scout.RB', 'scout.SG', 'status', 'status_id', 'variacao'],
      dtype='object')

In [12]:
rodada_38.drop(['apelido', 'clube.abreviacao', 'clube.mercado',
       'clube.nome', 'clube.slug', 'foto',
       'partida_clube_casa.abreviacao', 'partida_clube_casa.id',
       'partida_clube_casa.mercado', 'partida_clube_casa.nome',
       'partida_clube_casa.slug', 'partida_clube_visitante.abreviacao',
       'partida_clube_visitante.id', 'partida_clube_visitante.mercado',
       'partida_clube_visitante.nome', 'partida_clube_visitante.slug',
       'partida_data',  'posicao.abreviacao', 'posicao.id',
       'posicao.nome', 'status', 'status_id'], axis=1, inplace=True)
#rodada_38.drop_duplicates(inplace=True)

In [13]:
rodada_38.drop_duplicates(inplace=True)

In [14]:
rodada_38['Rodada']=38

In [15]:
rodada_38.columns

Index(['clube.id', 'id', 'jogos', 'media', 'pontos', 'preco', 'scout.A',
       'scout.CA', 'scout.CV', 'scout.DD', 'scout.DP', 'scout.FC', 'scout.FD',
       'scout.FF', 'scout.FS', 'scout.FT', 'scout.G', 'scout.GC', 'scout.GS',
       'scout.I', 'scout.PE', 'scout.PP', 'scout.RB', 'scout.SG', 'variacao',
       'Rodada'],
      dtype='object')

In [16]:
rodada_38.rename(columns={'clube.id': 'ClubeID','id': 'AtletaID', 'jogos':'Jogos',
                                  'pontos': 'Pontos', 'media':'PontosMedia','preco': 'Preco',
                                  'variacao': 'PrecoVariacao','scout.FS': 'FS','scout.PE': 'PE',
                                  'scout.A': 'A', 'scout.FT': 'FT','scout.FD': 'FD', 'scout.FF': 'FF', 
                                  'scout.G': 'G','scout.I': 'I', 'scout.PP':'PP', 'scout.RB': 'RB',
                                  'scout.FC':'FC','scout.GC': 'GC', 'scout.CA':'CA', 'scout.CV':'CV',
                                  'scout.SG': 'SG', 'scout.DD':'DD','scout.DP': 'DP','scout.GS':  'GS'},inplace=True)

In [17]:
rodada_38.head()

,ClubeID,AtletaID,Jogos,PontosMedia,Pontos,Preco,A,CA,CV,DD,DP,FC,FD,FF,FS,FT,G,GC,GS,I,PE,PP,RB,SG,PrecoVariacao,Rodada
0,284,86759,33,5.78,0.50,26.98,7.0,5.0,NaN,NaN,NaN,47.0,25.0,26.0,108.0,2.0,10.0,NaN,NaN,17.0,96.0,NaN,25.0,NaN,-1.32,38
1,292,68911,33,3.77,6.30,26.09,9.0,7.0,1.0,NaN,NaN,40.0,14.0,19.0,45.0,NaN,9.0,NaN,1.0,8.0,139.0,NaN,26.0,NaN,0.95,38
2,275,36612,26,5.20,5.30,24.83,4.0,1.0,NaN,NaN,NaN,15.0,8.0,10.0,30.0,NaN,2.0,NaN,NaN,3.0,42.0,NaN,37.0,6.0,-0.16,38
3,276,38055,22,5.24,0.00,24.69,NaN,1.0,NaN,27.0,1.0,NaN,NaN,NaN,1.0,NaN,3.0,NaN,20.0,NaN,18.0,NaN,NaN,10.0,0.00,38
4,282,63219,26,4.50,6.60,23.87,4.0,7.0,NaN,NaN,NaN,36.0,9.0,18.0,27.0,NaN,7.0,NaN,NaN,11.0,105.0,NaN,44.0,NaN,0.25,38

In [18]:
rodada_38 = rodada_38.apply(pd.to_numeric)

In [19]:
cols_scouts_def = ['CA','CV','DD','DP','FC','GC','GS','RB','SG'] # alphabetical order
cols_scouts_atk = ['A','FD','FF','FS','FT','G','I','PE','PP'] # alphabetical order
cols_scouts = cols_scouts_def + cols_scouts_atk

In [20]:
print('Colunas:', '\n', rodada_38.columns, '\n')
# this data have all player on Cartola dabase 2017, also have ClubeID, nickname and Position
# We will explore
print('Base: \n',rodada_38.head(), '\n')
print('Tamanaho da base: \n ', rodada_38.shape, '\n')
print('Quantidade de duplicados: \n', rodada_38.duplicated().value_counts(),  '\n') # This dataset doesn't have any duplicated
print('Quantidade de Atletas Missing: \n', rodada_38.AtletaID.isnull().sum(), '\n') # We have six positions of players on field , GK, DF, (RB and LF), MF, St, Coach
print('Quantidade de clubes Missing: \n', rodada_38.ClubeID.isnull().sum(),  '\n') # twenty teams
print('Quantidade de jogadores por rodada: ', rodada_38.Rodada.value_counts().sort_index())
print("RODADA 0 É ANTES DO GAME COMEÇAR, JOGADORES COM PONTOS ZERADO E VALOR INICIAL")
rodada_38['Scouts'] = rodada_38[cols_scouts].sum(axis=1)
rodada_38.sort_values(by=['AtletaID','Rodada', 'Jogos', 'Scouts', 'Pontos'],inplace=True)

Colunas:
 Index(['ClubeID', 'AtletaID', 'Jogos', 'PontosMedia', 'Pontos', 'Preco', 'A',
       'CA', 'CV', 'DD', 'DP', 'FC', 'FD', 'FF', 'FS', 'FT', 'G', 'GC', 'GS',
       'I', 'PE', 'PP', 'RB', 'SG', 'PrecoVariacao', 'Rodada'],
      dtype='object')

Base:
    ClubeID  AtletaID  Jogos  PontosMedia  Pontos  Preco    A   CA   CV    DD  \
0      284     86759     33         5.78     0.5  26.98  7.0  5.0  NaN   NaN
1      292     68911     33         3.77     6.3  26.09  9.0  7.0  1.0   NaN
2      275     36612     26         5.20     5.3  24.83  4.0  1.0  NaN   NaN
3      276     38055     22         5.24     0.0  24.69  NaN  1.0  NaN  27.0
4      282     63219     26         4.50     6.6  23.87  4.0  7.0  NaN   NaN

    DP    FC    FD    FF     FS   FT     G  GC    GS     I     PE  PP    RB  \
0  NaN  47.0  25.0  26.0  108.0  2.0  10.0 NaN   NaN  17.0   96.0 NaN  25.0
1  NaN  40.0  14.0  19.0   45.0  NaN   9.0 NaN   1.0   8.0  139.0 NaN  26.0
2  NaN  15.0   8.0  10.0   30.0  NaN   2.0 NaN   NaN   3.0   42.0 NaN  37.0
3  1.0   NaN   NaN   NaN    1.0  NaN   3.0 NaN  20.0   NaN   18.0 NaN   NaN
4  NaN  36.0   9.0  18.0   27.0  NaN   7.0 NaN   NaN  11.0  105.0 NaN  44.0

     SG  PrecoVariacao  Rodada
0   NaN          -1.32      38
1   NaN           0.95      38
2   6.0          -0.16      38
3  10.0           0.00      38
4   NaN           0.25      38

Tamanaho da base:
  (822, 26)

Quantidade de duplicados:
 False    822
dtype: int64

Quantidade de Atletas Missing:
 0

Quantidade de clubes Missing:
 0

Quantidade de jogadores por rodada:  38    822
Name: Rodada, dtype: int64
RODADA 0 É ANTES DO GAME COMEÇAR, JOGADORES COM PONTOS ZERADO E VALOR INICIAL

In [21]:
print('Tamanho da base de 2018 antes da limpeza', rodada_38.shape)
rodada_38['Ano'] = 2015
# Eliminando jogadores com nan no nome do clube e que não participaram de jogos
rodada_38 = rodada_38[rodada_38.Scouts>0]
rodada_38 = rodada_38[(rodada_38.PrecoVariacao != 0) | (rodada_38.Pontos!=0)]
rodada_38.drop_duplicates(subset=['AtletaID','ClubeID','Rodada'],keep='last', inplace=True)
print('Tamanho da base com apenas jogadores que jogaram:',rodada_38.shape)
rodada_38_limpo = rodada_38[(~rodada_38.ClubeID.isnull()) & (rodada_38.Rodada>0)]
print('Tamanho da base limpa:', rodada_38_limpo.shape)

rodada_38_limpo.sample(10)

Tamanho da base de 2018 antes da limpeza (822, 27)
Tamanho da base com apenas jogadores que jogaram: (280, 28)
Tamanho da base limpa: (280, 28)

,ClubeID,AtletaID,Jogos,PontosMedia,Pontos,Preco,A,CA,CV,DD,DP,FC,FD,FF,FS,FT,G,GC,GS,I,PE,PP,RB,SG,PrecoVariacao,Rodada,Scouts,Ano
28,292,78445,33,4.09,4.2,8.87,4.0,9.0,NaN,NaN,NaN,41.0,4.0,3.0,36.0,NaN,1.0,1.0,NaN,NaN,161.0,NaN,65.0,13.0,-1.48,38,338.0,2015
198,284,72491,13,1.91,4.7,5.32,NaN,5.0,NaN,NaN,NaN,13.0,NaN,1.0,6.0,NaN,1.0,NaN,NaN,NaN,30.0,NaN,8.0,5.0,0.47,38,69.0,2015
63,284,38139,20,2.99,6.9,7.95,2.0,1.0,NaN,NaN,NaN,7.0,6.0,9.0,11.0,NaN,5.0,NaN,NaN,9.0,17.0,NaN,4.0,NaN,1.25,38,71.0,2015
36,293,86764,24,4.00,8.8,8.63,2.0,5.0,NaN,NaN,NaN,30.0,3.0,8.0,26.0,1.0,2.0,NaN,NaN,1.0,74.0,NaN,28.0,9.0,0.86,38,189.0,2015
116,317,87399,22,3.10,1.1,6.83,NaN,5.0,NaN,NaN,NaN,44.0,2.0,7.0,23.0,NaN,1.0,NaN,NaN,NaN,74.0,NaN,33.0,8.0,0.13,38,197.0,2015
59,276,71123,34,3.47,0.5,8.00,3.0,7.0,NaN,NaN,NaN,48.0,9.0,11.0,60.0,NaN,1.0,NaN,NaN,4.0,96.0,NaN,69.0,NaN,-1.96,38,308.0,2015
156,267,50454,25,1.47,2.7,5.96,2.0,10.0,NaN,NaN,NaN,46.0,3.0,5.0,29.0,NaN,NaN,NaN,NaN,NaN,75.0,NaN,42.0,NaN,0.10,38,212.0,2015
756,316,38394,24,2.73,7.8,12.03,NaN,9.0,NaN,NaN,NaN,32.0,NaN,8.0,15.0,1.0,NaN,NaN,NaN,2.0,57.0,NaN,39.0,7.0,0.69,38,170.0,2015
209,275,50462,19,-0.09,-0.3,5.12,NaN,5.0,1.0,NaN,NaN,43.0,3.0,5.0,8.0,NaN,NaN,NaN,NaN,2.0,39.0,NaN,13.0,3.0,-0.64,38,122.0,2015
135,303,68951,19,1.27,1.4,6.40,1.0,6.0,NaN,NaN,NaN,40.0,2.0,7.0,18.0,NaN,NaN,NaN,NaN,NaN,64.0,NaN,32.0,NaN,0.26,38,170.0,2015

In [22]:
rodada_38_limpo.drop_duplicates(subset=['AtletaID','ClubeID','PontosMedia', 'Pontos', 'Preco', 'Rodada'],keep='last', inplace=True)

In [23]:
rodada_38_limpo.shape

(280, 28)

In [24]:
rodada_38_limpo.sample(30)

,ClubeID,AtletaID,Jogos,PontosMedia,Pontos,Preco,A,CA,CV,DD,DP,FC,FD,FF,FS,FT,G,GC,GS,I,PE,PP,RB,SG,PrecoVariacao,Rodada,Scouts,Ano
390,317,81612,11,1.26,0.0,3.36,NaN,1.0,NaN,NaN,NaN,18.0,4.0,5.0,7.0,NaN,1.0,NaN,NaN,3.0,15.0,NaN,7.0,NaN,-0.76,38,61.0,2015
454,290,90285,33,4.55,2.0,14.34,7.0,10.0,1.0,NaN,NaN,56.0,25.0,28.0,90.0,NaN,7.0,NaN,NaN,15.0,83.0,NaN,32.0,NaN,0.02,38,354.0,2015
505,294,86588,3,0.00,0.5,2.05,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.07,38,2.0,2015
156,267,50454,25,1.47,2.7,5.96,2.0,10.0,NaN,NaN,NaN,46.0,3.0,5.0,29.0,NaN,NaN,NaN,NaN,NaN,75.0,NaN,42.0,NaN,0.10,38,212.0,2015
812,316,80552,23,3.92,10.2,9.86,2.0,5.0,NaN,NaN,NaN,31.0,3.0,2.0,40.0,NaN,1.0,NaN,NaN,NaN,54.0,NaN,35.0,6.0,1.06,38,179.0,2015
186,267,37663,26,2.88,3.8,5.51,NaN,1.0,NaN,NaN,NaN,14.0,1.0,1.0,19.0,NaN,2.0,NaN,NaN,2.0,61.0,NaN,21.0,8.0,-0.70,38,130.0,2015
774,284,68821,33,3.69,5.5,11.38,2.0,8.0,NaN,NaN,NaN,39.0,13.0,16.0,38.0,2.0,2.0,NaN,NaN,6.0,155.0,NaN,33.0,15.0,0.88,38,329.0,2015
746,303,52674,32,2.55,-0.6,12.40,2.0,11.0,NaN,NaN,NaN,57.0,3.0,5.0,43.0,NaN,NaN,NaN,NaN,6.0,98.0,NaN,42.0,11.0,0.49,38,278.0,2015
752,290,84848,26,4.59,0.2,12.14,2.0,4.0,NaN,NaN,NaN,12.0,8.0,8.0,26.0,2.0,10.0,NaN,NaN,9.0,49.0,NaN,17.0,NaN,-1.29,38,147.0,2015
23,282,85027,20,1.35,-0.5,8.95,1.0,3.0,1.0,NaN,NaN,14.0,2.0,8.0,11.0,NaN,3.0,NaN,NaN,5.0,22.0,NaN,7.0,NaN,-0.17,38,77.0,2015
67,262,69022,21,1.35,1.5,7.84,2.0,3.0,NaN,NaN,NaN,13.0,8.0,2.0,24.0,1.0,1.0,NaN,NaN,9.0,49.0,NaN,10.0,NaN,0.33,38,122.0,2015
556,266,85626,6,1.58,-0.5,1.99,1.0,NaN,NaN,NaN,NaN,7.0,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,20.0,NaN,4.0,1.0,0.07,38,37.0,2015
763,294,50284,27,4.80,8.0,11.65,NaN,3.0,NaN,41.0,NaN,1.0,NaN,NaN,5.0,NaN,NaN,NaN,25.0,NaN,14.0,NaN,NaN,13.0,0.20,38,102.0,2015
176,317,37781,12,0.42,0.7,5.64,1.0,3.0,NaN,NaN,NaN,10.0,1.0,6.0,11.0,NaN,NaN,NaN,NaN,2.0,18.0,NaN,4.0,NaN,-0.30,38,56.0,2015
450,262,68958,28,4.41,1.6,14.78,1.0,5.0,NaN,NaN,NaN,36.0,6.0,6.0,36.0,1.0,1.0,NaN,NaN,1.0,77.0,NaN,56.0,7.0,0.00,38,233.0,2015
783,285,38219,23,2.53,-1.1,11.00,2.0,3.0,NaN,NaN,NaN,17.0,11.0,10.0,50.0,1.0,1.0,NaN,NaN,4.0,78.0,NaN,20.0,NaN,-0.79,38,197.0,2015
456,266,71892,28,3.27,1.2,14.26,NaN,5.0,NaN,NaN,NaN,35.0,NaN,9.0,40.0,NaN,1.0,NaN,NaN,4.0,123.0,NaN,49.0,8.0,-0.53,38,274.0,2015
131,294,37705,15,4.24,3.1,6.54,2.0,1.0,NaN,NaN,NaN,14.0,1.0,4.0,16.0,NaN,3.0,NaN,NaN,2.0,36.0,NaN,8.0,5.0,-1.30,38,92.0,2015
347,303,51495,12,2.45,-0.6,3.81,NaN,2.0,1.0,NaN,NaN,10.0,NaN,2.0,5.0,NaN,2.0,NaN,NaN,1.0,21.0,NaN,6.0,4.0,-1.17,38,54.0,2015
129,292,73957,7,2.54,5.0,6.56,1.0,NaN,NaN,NaN,NaN,2.0,1.0,1.0,5.0,NaN,NaN,NaN,NaN,NaN,7.0,NaN,1.0,2.0,-0.21,38,20.0,2015
705,290,38278,11,0.10,-1.1,0.83,NaN,2.0,NaN,NaN,NaN,6.0,1.0,5.0,8.0,NaN,NaN,NaN,NaN,NaN,7.0,NaN,1.0,NaN,-0.03,38,30.0,2015
220,290,37899,35,3.05,1.0,18.34,NaN,4.0,NaN,50.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,43.0,NaN,21.0,NaN,NaN,11.0,-0.09,38,133.0,2015
677,282,68929,31,3.13,7.5,13.10,2.0,3.0,NaN,NaN,NaN,19.0,13.0,19.0,23.0,NaN,9.0,NaN,NaN,9.0,85.0,NaN,13.0,NaN,1.30,38,195.0,2015
332,266,80188,30,1.42,-1.4,3.95,1.0,11.0,1.0,NaN,NaN,38.0,11.0,9.0,58.0,NaN,5.0,NaN,NaN,6.0,55.0,NaN,10.0,NaN,-0.55,38,205.0,2015
110,314,60794,27,1.73,1.2,6.90,NaN,3.0,NaN,NaN,NaN,20.0,3.0,7.0,53.0,NaN,NaN,NaN,NaN,2.0,71.0,NaN,21.0,3.0,0.08,38,183.0,2015
693,266,91815,2,0.40,0.5,0.92,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,3.0,NaN,0.03,38,13.0,2015
32,316,77529,31,3.16,10.0,8.74,2.0,9.0,1.0,NaN,NaN,54.0,1.0,7.0,26.0,NaN,1.0,1.0,NaN,NaN,106.0,NaN,67.0,7.0,1.65,38,282.0,2015
193,317,71724,32,3.76,-4.0,5.40,NaN,1.0,NaN,46.0,2.0,1.0,NaN,NaN,5.0,NaN,NaN,NaN,38.0,NaN,19.0,NaN,NaN,10.0,-1.18,38,122.0,2015
52,292,73384,30,2.44,5.9,8.29,2.0,6.0,1.0,NaN,NaN,30.0,NaN,7.0,34.0,NaN,1.0,2.0,NaN,1.0,87.0,NaN,23.0,13.0,-0.11,38,207.0,2015
707,293,63082,1,-7.00,-7.0,0.83,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,-1.17,38,6.0,2015

#### Adicionando a 26 Rodada

In [25]:
path = "D:\\Dropbox\\Projeto Brasileirao\\caRtola\\data\\2015\\raw\\CartolaFC 2015 - Rodada 26 - 2015-9-15\\26\\"
files = os.listdir(path)
path2 = "D:\\Dropbox\\Projeto Brasileirao\\caRtola\\data\\2015\\raw\\CartolaFC 2015 - Rodada 26 - 2015-9-16\\26\\"
files2 = os.listdir(path2)
data = []

In [50]:
data[0]

{'atleta': [{'apelido': 'Rogério Ceni',
   'clube': {'abreviacao': 'sao',
    'id': 276,
    'mercado': 1,
    'nome': 'são paulo',
    'slug': 'sao-paulo'},
   'foto': 'http://s.glbimg.com/es/sde/f/2010/11/16/26a2befe651824215d84a88996adb9d9_FORMATO.jpeg',
   'id': 38055,
   'jogos': 16,
   'media': '5.89',
   'partida_clube_casa': {'abreviacao': 'sao',
    'id': 276,
    'mercado': 1,
    'nome': 'são paulo',
    'slug': 'sao-paulo'},
   'partida_clube_visitante': {'abreviacao': 'cha',
    'id': 315,
    'mercado': 1,
    'nome': 'chapecoense',
    'slug': 'chapecoense'},
   'partida_data': '17/09/2015',
   'pontos': '0.00',
   'posicao': {'abreviacao': 'GOL', 'id': 1, 'nome': 'Goleiro'},
   'preco': '28.20',
   'scout': {'CA': 1,
    'DD': 19,
    'DP': 1,
    'FS': 1,
    'G': 3,
    'GS': 14,
    'PE': 15,
    'SG': 8},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '0.00'},
  {'apelido': 'Zé Roberto',
   'clube': {'abreviacao': 'pal',
    'id': 275,
    'mercado': 1,
    'nome': 'palmeiras',
    'slug': 'palmeiras'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/16/1f353020166f7411ccb776b393896287_FORMATO.jpeg',
   'id': 36612,
   'jogos': 18,
   'media': '6.50',
   'partida_clube_casa': {'abreviacao': 'flu',
    'id': 266,
    'mercado': 1,
    'nome': 'fluminense',
    'slug': 'fluminense'},
   'partida_clube_visitante': {'abreviacao': 'pal',
    'id': 275,
    'mercado': 1,
    'nome': 'palmeiras',
    'slug': 'palmeiras'},
   'partida_data': '16/09/2015',
   'pontos': '15.60',
   'posicao': {'abreviacao': 'LAT', 'id': 2, 'nome': 'Lateral'},
   'preco': '27.43',
   'scout': {'A': 3,
    'FC': 7,
    'FD': 6,
    'FF': 8,
    'FS': 23,
    'G': 2,
    'PE': 26,
    'RB': 26,
    'SG': 6},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '2.45'},
  {'apelido': 'Luan',
   'clube': {'abreviacao': 'gre',
    'id': 284,
    'mercado': 1,
    'nome': 'grêmio',
    'slug': 'gremio'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/07/22/e41afa12b4fd05085d1302afcbf9e45b_FORMATO.jpeg',
   'id': 86759,
   'jogos': 21,
   'media': '5.71',
   'partida_clube_casa': {'abreviacao': 'atl',
    'id': 293,
    'mercado': 1,
    'nome': 'atlético-pr',
    'slug': 'atletico-pr'},
   'partida_clube_visitante': {'abreviacao': 'gre',
    'id': 284,
    'mercado': 1,
    'nome': 'grêmio',
    'slug': 'gremio'},
   'partida_data': '16/09/2015',
   'pontos': '3.40',
   'posicao': {'abreviacao': 'ATA', 'id': 5, 'nome': 'Atacante'},
   'preco': '27.21',
   'scout': {'A': 4,
    'CA': 3,
    'FC': 30,
    'FD': 16,
    'FF': 18,
    'FS': 75,
    'FT': 2,
    'G': 5,
    'I': 12,
    'PE': 62,
    'RB': 19},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '-0.73'},
  {'apelido': 'Diego Souza',
   'clube': {'abreviacao': 'spo',
    'id': 292,
    'mercado': 1,
    'nome': 'sport',
    'slug': 'sport'},
   'foto': 'http://s.glbimg.com/es/sde/f/2010/11/16/1a8619488e59272cfcd67e37c094f42c_FORMATO.jpeg',
   'id': 68911,
   'jogos': 24,
   'media': '3.51',
   'partida_clube_casa': {'abreviacao': 'jec',
    'id': 317,
    'mercado': 1,
    'nome': 'joinville',
    'slug': 'joinville'},
   'partida_clube_visitante': {'abreviacao': 'spo',
    'id': 292,
    'mercado': 1,
    'nome': 'sport',
    'slug': 'sport'},
   'partida_data': '16/09/2015',
   'pontos': '0.70',
   'posicao': {'abreviacao': 'MEI', 'id': 4, 'nome': 'Meia'},
   'preco': '25.77',
   'scout': {'A': 5,
    'CA': 5,
    'FC': 33,
    'FD': 10,
    'FF': 15,
    'FS': 33,
    'G': 6,
    'GS': 1,
    'I': 6,
    'PE': 101,
    'RB': 21},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '-0.19'},
  {'apelido': 'Paolo Guerrero',
   'clube': {'abreviacao': 'fla',
    'id': 262,
    'mercado': 1,
    'nome': 'flamengo',
    'slug': 'flamengo'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/07/09/1794a20985c424c3ab6a310bb31bcd2b_FORMATO.jpeg',
   'id': 75295,
   'jogos': 9,
   'media': '6.32',
   'partida_clube_casa': {'abreviacao': 'fla',
    'id': 262,
    'mercado': 1,
    'nome': 'flamengo',
    'slug': 'flamengo'},
   'partida_clube_visitante': {'abreviacao': 'cor',
    'id': 294,
    'mercado': 1,
    'nome': 'coritiba',
    'slug': 'coritiba'},
   'partida_data': '17/09/2015',
   'pontos': '0.00',
   'posicao': {'abreviacao': 'ATA', 'id': 5, 'nome': 'Atacante'},
   'preco': '23.80',
   'scout': {'A': 2,
    'CA': 3,
    'FC': 17,
    'FD': 13,
    'FF': 14,
    'FS': 23,
    'FT': 1,
    'G': 3,
    'I': 10,
    'PE': 13,
    'RB': 5},
   'status': 'Contundido',
   'status_id': 5,
   'variacao': '0.00'},
  {'apelido': 'Luan',
   'clube': {'abreviacao': 'atl',
    'id': 282,
    'mercado': 1,
    'nome': 'atlético-mg',
    'slug': 'atletico-mg'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/19/e321ce47e7e74ec473f8bfb24f10fa17_FORMATO.jpeg',
   'id': 63219,
   'jogos': 14,
   'media': '4.04',
   'partida_clube_casa': {'abreviacao': 'san',
    'id': 277,
    'mercado': 1,
    'nome': 'santos',
    'slug': 'santos'},
   'partida_clube_visitante': {'abreviacao': 'atl',
    'id': 282,
    'mercado': 1,
    'nome': 'atlético-mg',
    'slug': 'atletico-mg'},
   'partida_data': '16/09/2015',
   'pontos': '4.30',
   'posicao': {'abreviacao': 'ATA', 'id': 5, 'nome': 'Atacante'},
   'preco': '23.49',
   'scout': {'A': 3,
    'CA': 3,
    'FC': 18,
    'FD': 4,
    'FF': 7,
    'FS': 13,
    'G': 3,
    'I': 9,
    'PE': 58,
    'RB': 23},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '-1.49'},
  {'apelido': 'Fred',
   'clube': {'abreviacao': 'flu',
    'id': 266,
    'mercado': 1,
    'nome': 'fluminense',
    'slug': 'fluminense'},
   'foto': 'http://s.glbimg.com/es/sde/f/2014/06/11/558840826d114d32d4785adf70f69146_FORMATO.jpeg',
   'id': 38162,
   'jogos': 16,
   'media': '5.41',
   'partida_clube_casa': {'abreviacao': 'flu',
    'id': 266,
    'mercado': 1,
    'nome': 'fluminense',
    'slug': 'fluminense'},
   'partida_clube_visitante': {'abreviacao': 'pal',
    'id': 275,
    'mercado': 1,
    'nome': 'palmeiras',
    'slug': 'palmeiras'},
   'partida_data': '16/09/2015',
   'pontos': '-1.40',
   'posicao': {'abreviacao': 'ATA', 'id': 5, 'nome': 'Atacante'},
   'preco': '22.71',
   'scout': {'A': 3,
    'CA': 1,
    'FC': 26,
    'FD': 12,
    'FF': 11,
    'FS': 45,
    'FT': 1,
    'G': 6,
    'I': 6,
    'PE': 42,
    'RB': 5},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '-1.16'},
  {'apelido': 'Weverton',
   'clube': {'abreviacao': 'atl',
    'id': 293,
    'mercado': 1,
    'nome': 'atlético-pr',
    'slug': 'atletico-pr'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/03/04/be979300c75e0d1bbbd0203881eb8af8_FORMATO.png',
   'id': 71631,
   'jogos': 24,
   'media': '4.95',
   'partida_clube_casa': {'abreviacao': 'atl',
    'id': 293,
    'mercado': 1,
    'nome': 'atlético-pr',
    'slug': 'atletico-pr'},
   'partida_clube_visitante': {'abreviacao': 'gre',
    'id': 284,
    'mercado': 1,
    'nome': 'grêmio',
    'slug': 'gremio'},
   'partida_data': '16/09/2015',
   'pontos': '7.70',
   'posicao': {'abreviacao': 'GOL', 'id': 1, 'nome': 'Goleiro'},
   'preco': '22.55',
   'scout': {'CA': 5,
    'DD': 36,
    'DP': 3,
    'FS': 10,
    'GS': 24,
    'PE': 24,
    'SG': 10},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '1.23'},
  {'apelido': 'Lucas Pratto',
   'clube': {'abreviacao': 'atl',
    'id': 282,
    'mercado': 1,
    'nome': 'atlético-mg',
    'slug': 'atletico-mg'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/07/22/3ee27b784c87bfb5b52d2e0e029b9623_FORMATO.jpeg',
   'id': 73649,
   'jogos': 21,
   'media': '5.67',
   'partida_clube_casa': {'abreviacao': 'san',
    'id': 277,
    'mercado': 1,
    'nome': 'santos',
    'slug': 'santos'},
   'partida_clube_visitante': {'abreviacao': 'atl',
    'id': 282,
    'mercado': 1,
    'nome': 'atlético-mg',
    'slug': 'atletico-mg'},
   'partida_data': '16/09/2015',
   'pontos': '4.40',
   'posicao': {'abreviacao': 'ATA', 'id': 5, 'nome': 'Atacante'},
   'preco': '22.51',
   'scout': {'A': 1,
    'CA': 1,
    'FC': 22,
    'FD': 24,
    'FF': 25,
    'FS': 32,
    'FT': 4,
    'G': 7,
    'I': 10,
    'PE': 64,
    'RB': 14},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '0.06'},
  {'apelido': 'Marcelo Lomba',
   'clube': {'abreviacao': 'pon',
    'id': 303,
    'mercado': 1,
    'nome': 'ponte preta',
    'slug': 'ponte-preta'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/05/07/c617183d096aa584576435e1d179a129_FORMATO.jpeg',
   'id': 68872,
   'jogos': 25,
   'media': '6.36',
   'partida_clube_casa': {'abreviacao': 'goi',
    'id': 290,
    'mercado': 1,
    'nome': 'goiás',
    'slug': 'goias'},
   'partida_clube_visitante': {'abreviacao': 'pon',
    'id': 303,
    'mercado': 1,
    'nome': 'ponte preta',
    'slug': 'ponte-preta'},
   'partida_data': '16/09/2015',
   'pontos': '13.00',
   'posicao': {'abreviacao': 'GOL', 'id': 1, 'nome': 'Goleiro'},
   'preco': '22.15',
   'scout': {'DD': 55, 'DP': 1, 'FS': 4, 'GS': 28, 'PE': 14, 'SG': 9},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '2.12'},
  {'apelido': 'Rodinei',
   'clube': {'abreviacao': 'pon',
    'id': 303,
    'mercado': 1,
    'nome': 'ponte preta',
    'slug': 'ponte-preta'},
   'foto': 'http://s.glbimg.com/es/sde/f/2012/06/12/d42019108f0818dcf21213898cf8c711_FORMATO.png',
   'id': 73992,
   'jogos': 25,
   'media': '5.12',
   'partida_clube_casa': {'abreviacao': 'goi',
    'id': 290,
    'mercado': 1,
    'nome': 'goiás',
    'slug': 'goias'},
   'partida_clube_visitante': {'abreviacao': 'pon',
    'id': 303,
    'mercado': 1,
    'nome': 'ponte preta',
    'slug': 'ponte-preta'},
   'partida_data': '16/09/2015',
   'pontos': '2.20',
   'posicao': {'abreviacao': 'LAT', 'id': 2, 'nome': 'Lateral'},
   'preco': '22.10',
   'scout': {'A': 4,
    'FC': 27,
    'FD': 3,
    'FF': 7,
    'FS': 23,
    'FT': 1,
    'I': 3,
    'PE': 65,
    'RB': 44,
    'SG': 9},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '-0.37'},
  {'apelido': 'Everton',
   'clube': {'abreviacao': 'fla',
    'id': 262,
    'mercado': 1,
    'nome': 'flamengo',
    'slug': 'flamengo'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/15/3e69d11d0318f680bf3b3f14653ec742_FORMATO.jpeg',
   'id': 50301,
   'jogos': 23,
   'media': '3.54',
   'partida_clube_casa': {'abreviacao': 'fla',
    'id': 262,
    'mercado': 1,
    'nome': 'flamengo',
    'slug': 'flamengo'},
   'partida_clube_visitante': {'abreviacao': 'cor',
    'id': 294,
    'mercado': 1,
    'nome': 'coritiba',
    'slug': 'coritiba'},
   'partida_data': '17/09/2015',
   'pontos': '10.80',
   'posicao': {'abreviacao': 'MEI', 'id': 4, 'nome': 'Meia'},
   'preco': '22.04',
   'scout': {'A': 2,
    'CA': 5,
    'CV': 1,
    'FC': 32,
    'FD': 10,
    'FF': 7,
    'FS': 44,
    'G': 4,
    'I': 19,
    'PE': 77,
    'RB': 39},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '2.40'},
  {'apelido': 'Rodrigo',
   'clube': {'abreviacao': 'vas',
    'id': 267,
    'mercado': 1,
    'nome': 'vasco',
    'slug': 'vasco'},
   'foto': 'http://s.glbimg.com/es/sde/f/2010/11/18/d4c557ca26c062f0b9991a8d8e4067fa_FORMATO.jpeg',
   'id': 37644,
   'jogos': 22,
   'media': '4.92',
   'partida_clube_casa': {'abreviacao': 'cru',
    'id': 283,
    'mercado': 1,
    'nome': 'cruzeiro',
    'slug': 'cruzeiro'},
   'partida_clube_visitante': {'abreviacao': 'vas',
    'id': 267,
    'mercado': 1,
    'nome': 'vasco',
    'slug': 'vasco'},
   'partida_data': '16/09/2015',
   'pontos': '15.00',
   'posicao': {'abreviacao': 'ZAG', 'id': 3, 'nome': 'Zagueiro'},
   'preco': '21.35',
   'scout': {'CA': 5,
    'CV': 1,
    'FC': 21,
    'FD': 15,
    'FF': 15,
    'FS': 26,
    'G': 1,
    'I': 2,
    'PE': 72,
    'RB': 44,
    'SG': 7},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '1.40'},
  {'apelido': 'Cássio',
   'clube': {'abreviacao': 'cor',
    'id': 264,
    'mercado': 1,
    'nome': 'corinthians',
    'slug': 'corinthians'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/15/210bd6815119826cf3f44b175d9ff09d_FORMATO.jpeg',
   'id': 42234,
   'jogos': 23,
   'media': '4.85',
   'partida_clube_casa': {'abreviacao': 'int',
    'id': 285,
    'mercado': 1,
    'nome': 'internacional',
    'slug': 'internacional'},
   'partida_clube_visitante': {'abreviacao': 'cor',
    'id': 264,
    'mercado': 1,
    'nome': 'corinthians',
    'slug': 'corinthians'},
   'partida_data': '16/09/2015',
   'pontos': '8.00',
   'posicao': {'abreviacao': 'GOL', 'id': 1, 'nome': 'Goleiro'},
   'preco': '21.34',
   'scout': {'CA': 2, 'DD': 34, 'FS': 2, 'GS': 19, 'PE': 14, 'SG': 11},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '1.63'},
  {'apelido': 'Edson',
   'clube': {'abreviacao': 'flu',
    'id': 266,
    'mercado': 1,
    'nome': 'fluminense',
    'slug': 'fluminense'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/15/04123fe6d4dc83b6ecf6f00bd9aef208_FORMATO.jpeg',
   'id': 80370,
   'jogos': 22,
   'media': '4.27',
   'partida_clube_casa': {'abreviacao': 'flu',
    'id': 266,
    'mercado': 1,
    'nome': 'fluminense',
    'slug': 'fluminense'},
   'partida_clube_visitante': {'abreviacao': 'pal',
    'id': 275,
    'mercado': 1,
    'nome': 'palmeiras',
    'slug': 'palmeiras'},
   'partida_data': '16/09/2015',
   'pontos': '-1.70',
   'posicao': {'abreviacao': 'MEI', 'id': 4, 'nome': 'Meia'},
   'preco': '20.82',
   'scout': {'CA': 7,
    'FC': 41,
    'FD': 3,
    'FF': 15,
    'FS': 33,
    'FT': 1,
    'G': 2,
    'I': 2,
    'PE': 56,
    'RB': 57},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '-0.40'},
  {'apelido': 'Leandro Damião',
   'clube': {'abreviacao': 'cru',
    'id': 283,
    'mercado': 1,
    'nome': 'cruzeiro',
    'slug': 'cruzeiro'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/08/31/19c4446032c672320264b450e0c790a1_FORMATO.jpeg',
   'id': 68953,
   'jogos': 15,
   'media': '2.66',
   'partida_clube_casa': {'abreviacao': 'cru',
    'id': 283,
    'mercado': 1,
    'nome': 'cruzeiro',
    'slug': 'cruzeiro'},
   'partida_clube_visitante': {'abreviacao': 'vas',
    'id': 267,
    'mercado': 1,
    'nome': 'vasco',
    'slug': 'vasco'},
   'partida_data': '16/09/2015',
   'pontos': '0.00',
   'posicao': {'abreviacao': 'ATA', 'id': 5, 'nome': 'Atacante'},
   'preco': '19.68',
   'scout': {'A': 2,
    'CA': 3,
    'FC': 14,
    'FD': 10,
    'FF': 7,
    'FS': 19,
    'G': 2,
    'I': 5,
    'PE': 23,
    'RB': 7},
   'status': 'Contundido',
   'status_id': 5,
   'variacao': '0.00'},
  {'apelido': 'Rafael Marques',
   'clube': {'abreviacao': 'pal',
    'id': 275,
    'mercado': 1,
    'nome': 'palmeiras',
    'slug': 'palmeiras'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/19/410656f70157606547aad852b5090adb_FORMATO.jpeg',
   'id': 38957,
   'jogos': 23,
   'media': '4.45',
   'partida_clube_casa': {'abreviacao': 'flu',
    'id': 266,
    'mercado': 1,
    'nome': 'fluminense',
    'slug': 'fluminense'},
   'partida_clube_visitante': {'abreviacao': 'pal',
    'id': 275,
    'mercado': 1,
    'nome': 'palmeiras',
    'slug': 'palmeiras'},
   'partida_data': '16/09/2015',
   'pontos': '12.70',
   'posicao': {'abreviacao': 'ATA', 'id': 5, 'nome': 'Atacante'},
   'preco': '19.46',
   'scout': {'A': 4,
    'FC': 19,
    'FD': 11,
    'FF': 15,
    'FS': 36,
    'G': 6,
    'I': 8,
    'PE': 85,
    'RB': 20},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '2.51'},
  {'apelido': "D'Alessandro",
   'clube': {'abreviacao': 'int',
    'id': 285,
    'mercado': 1,
    'nome': 'internacional',
    'slug': 'internacional'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/15/408ea81f655217e1f98e651fe059d2eb_FORMATO.jpeg',
   'id': 62023,
   'jogos': 8,
   'media': '1.02',
   'partida_clube_casa': {'abreviacao': 'int',
    'id': 285,
    'mercado': 1,
    'nome': 'internacional',
    'slug': 'internacional'},
   'partida_clube_visitante': {'abreviacao': 'cor',
    'id': 264,
    'mercado': 1,
    'nome': 'corinthians',
    'slug': 'corinthians'},
   'partida_data': '16/09/2015',
   'pontos': '0.00',
   'posicao': {'abreviacao': 'MEI', 'id': 4, 'nome': 'Meia'},
   'preco': '19.41',
   'scout': {'A': 2,
    'CA': 4,
    'FC': 3,
    'FD': 2,
    'FF': 4,
    'FS': 20,
    'I': 1,
    'PE': 50,
    'PP': 1,
    'RB': 7},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '0.00'},
  {'apelido': 'Gil',
   'clube': {'abreviacao': 'cor',
    'id': 264,
    'mercado': 1,
    'nome': 'corinthians',
    'slug': 'corinthians'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/01/15/03fc334cdc2283ad2a8614b53cdc9816_FORMATO.jpeg',
   'id': 68923,
   'jogos': 21,
   'media': '3.23',
   'partida_clube_casa': {'abreviacao': 'int',
    'id': 285,
    'mercado': 1,
    'nome': 'internacional',
    'slug': 'internacional'},
   'partida_clube_visitante': {'abreviacao': 'cor',
    'id': 264,
    'mercado': 1,
    'nome': 'corinthians',
    'slug': 'corinthians'},
   'partida_data': '16/09/2015',
   'pontos': '7.20',
   'posicao': {'abreviacao': 'ZAG', 'id': 3, 'nome': 'Zagueiro'},
   'preco': '18.90',
   'scout': {'CA': 6,
    'FC': 14,
    'FD': 4,
    'FF': 3,
    'FS': 7,
    'FT': 1,
    'I': 1,
    'PE': 27,
    'RB': 16,
    'SG': 11},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '1.07'},
  {'apelido': 'Renan',
   'clube': {'abreviacao': 'goi',
    'id': 290,
    'mercado': 1,
    'nome': 'goiás',
    'slug': 'goias'},
   'foto': 'http://s.glbimg.com/es/sde/f/2015/07/22/0b1e40820556ff66c00e75f7298a0372_FORMATO.jpeg',
   'id': 37899,
   'jogos': 25,
   'media': '4.33',
   'partida_clube_casa': {'abreviacao': 'goi',
    'id': 290,
    'mercado': 1,
    'nome': 'goiás',
    'slug': 'goias'},
   'partida_clube_visitante': {'abreviacao': 'pon',
    'id': 303,
    'mercado': 1,
    'nome': 'ponte preta',
    'slug': 'ponte-preta'},
   'partida_data': '16/09/2015',
   'pontos': '-3.50',
   'posicao': {'abreviacao': 'GOL', 'id': 1, 'nome': 'Goleiro'},
   'preco': '18.87',
   'scout': {'CA': 2, 'DD': 35, 'FS': 4, 'GS': 23, 'PE': 13, 'SG': 11},
   'status': 'Provável',
   'status_id': 7,
   'variacao': '-3.10'}],
 'page': {'atual': '1', 'total': '42'},
 'rodada_id': 26}

In [26]:
for file in files:
    f = path+file    
    with open(f) as data_file:    
        data.append(json.load(data_file))
for file in files2:
    f = path2+file    
    with open(f) as data_file:    
        data.append(json.load(data_file))

In [27]:
for x in data[0]:
    print(x)

rodada_id
page
atleta

# Processamento

In [28]:
def prepara_scouts(loaded_json):
    aux = {}
    for i in loaded_json['atleta']:
        for j in i['scout']:
            aux.update({j['nome']:j['quantidade']})
        i['scout'] = aux
        aux = {}
    return loaded_json

In [29]:
for load in data:
    prepara_scouts(load)

In [30]:
rodada_26 = pd.DataFrame()
for file in data:
    rodada_26 = rodada_26.append(json_normalize(file['atleta']), ignore_index=True)

In [31]:
rodada_26.shape

(1664, 47)

In [32]:
rodada_26.duplicated().value_counts()

False    924
True     740
dtype: int64

In [33]:
rodada_26.drop_duplicates(inplace=True)

In [34]:
rodada_26.columns

Index(['apelido', 'clube.abreviacao', 'clube.id', 'clube.mercado',
       'clube.nome', 'clube.slug', 'foto', 'id', 'jogos', 'media',
       'partida_clube_casa.abreviacao', 'partida_clube_casa.id',
       'partida_clube_casa.mercado', 'partida_clube_casa.nome',
       'partida_clube_casa.slug', 'partida_clube_visitante.abreviacao',
       'partida_clube_visitante.id', 'partida_clube_visitante.mercado',
       'partida_clube_visitante.nome', 'partida_clube_visitante.slug',
       'partida_data', 'pontos', 'posicao.abreviacao', 'posicao.id',
       'posicao.nome', 'preco', 'scout.A', 'scout.CA', 'scout.CV', 'scout.DD',
       'scout.DP', 'scout.FC', 'scout.FD', 'scout.FF', 'scout.FS', 'scout.FT',
       'scout.G', 'scout.GC', 'scout.GS', 'scout.I', 'scout.PE', 'scout.PP',
       'scout.RB', 'scout.SG', 'status', 'status_id', 'variacao'],
      dtype='object')

In [35]:
rodada_26.drop(['apelido', 'clube.abreviacao', 'clube.mercado',
       'clube.nome', 'clube.slug', 'foto',
       'partida_clube_casa.abreviacao', 'partida_clube_casa.id',
       'partida_clube_casa.mercado', 'partida_clube_casa.nome',
       'partida_clube_casa.slug', 'partida_clube_visitante.abreviacao',
       'partida_clube_visitante.id', 'partida_clube_visitante.mercado',
       'partida_clube_visitante.nome', 'partida_clube_visitante.slug',
       'partida_data',  'posicao.abreviacao', 'posicao.id',
       'posicao.nome', 'status', 'status_id'], axis=1, inplace=True)
#rodada_38.drop_duplicates(inplace=True)

In [36]:
rodada_26.drop_duplicates(inplace=True)

In [37]:
rodada_26['Rodada']=26

In [38]:
rodada_26.columns

Index(['clube.id', 'id', 'jogos', 'media', 'pontos', 'preco', 'scout.A',
       'scout.CA', 'scout.CV', 'scout.DD', 'scout.DP', 'scout.FC', 'scout.FD',
       'scout.FF', 'scout.FS', 'scout.FT', 'scout.G', 'scout.GC', 'scout.GS',
       'scout.I', 'scout.PE', 'scout.PP', 'scout.RB', 'scout.SG', 'variacao',
       'Rodada'],
      dtype='object')

In [39]:
rodada_26.rename(columns={'clube.id': 'ClubeID','id': 'AtletaID', 'jogos':'Jogos',
                                  'pontos': 'Pontos', 'media':'PontosMedia','preco': 'Preco',
                                  'variacao': 'PrecoVariacao','scout.FS': 'FS','scout.PE': 'PE',
                                  'scout.A': 'A', 'scout.FT': 'FT','scout.FD': 'FD', 'scout.FF': 'FF', 
                                  'scout.G': 'G','scout.I': 'I', 'scout.PP':'PP', 'scout.RB': 'RB',
                                  'scout.FC':'FC','scout.GC': 'GC', 'scout.CA':'CA', 'scout.CV':'CV',
                                  'scout.SG': 'SG', 'scout.DD':'DD','scout.DP': 'DP','scout.GS':  'GS'},inplace=True)

In [40]:
rodada_26.head()

,ClubeID,AtletaID,Jogos,PontosMedia,Pontos,Preco,A,CA,CV,DD,DP,FC,FD,FF,FS,FT,G,GC,GS,I,PE,PP,RB,SG,PrecoVariacao,Rodada
0,276,38055,16,5.89,0.00,28.20,NaN,1.0,NaN,19.0,1.0,NaN,NaN,NaN,1.0,NaN,3.0,NaN,14.0,NaN,15.0,NaN,NaN,8.0,0.00,26
1,275,36612,18,6.50,15.60,27.43,3.0,NaN,NaN,NaN,NaN,7.0,6.0,8.0,23.0,NaN,2.0,NaN,NaN,NaN,26.0,NaN,26.0,6.0,2.45,26
2,284,86759,21,5.71,3.40,27.21,4.0,3.0,NaN,NaN,NaN,30.0,16.0,18.0,75.0,2.0,5.0,NaN,NaN,12.0,62.0,NaN,19.0,NaN,-0.73,26
3,292,68911,24,3.51,0.70,25.77,5.0,5.0,NaN,NaN,NaN,33.0,10.0,15.0,33.0,NaN,6.0,NaN,1.0,6.0,101.0,NaN,21.0,NaN,-0.19,26
4,262,75295,9,6.32,0.00,23.80,2.0,3.0,NaN,NaN,NaN,17.0,13.0,14.0,23.0,1.0,3.0,NaN,NaN,10.0,13.0,NaN,5.0,NaN,0.00,26

In [41]:
rodada_26 = rodada_26.apply(pd.to_numeric)

In [42]:
cols_scouts_def = ['CA','CV','DD','DP','FC','GC','GS','RB','SG'] # alphabetical order
cols_scouts_atk = ['A','FD','FF','FS','FT','G','I','PE','PP'] # alphabetical order
cols_scouts = cols_scouts_def + cols_scouts_atk

In [43]:
print('Colunas:', '\n', rodada_26.columns, '\n')
# this data have all player on Cartola dabase 2017, also have ClubeID, nickname and Position
# We will explore
print('Base: \n',rodada_26.head(), '\n')
print('Tamanaho da base: \n ', rodada_26.shape, '\n')
print('Quantidade de duplicados: \n', rodada_26.duplicated().value_counts(),  '\n') # This dataset doesn't have any duplicated
print('Quantidade de Atletas Missing: \n', rodada_26.AtletaID.isnull().sum(), '\n') # We have six positions of players on field , GK, DF, (RB and LF), MF, St, Coach
print('Quantidade de clubes Missing: \n', rodada_26.ClubeID.isnull().sum(),  '\n') # twenty teams
print('Quantidade de jogadores por rodada: ', rodada_26.Rodada.value_counts().sort_index())
print("RODADA 0 É ANTES DO GAME COMEÇAR, JOGADORES COM PONTOS ZERADO E VALOR INICIAL")
rodada_26['Scouts'] = rodada_26[cols_scouts].sum(axis=1)
rodada_26.sort_values(by=['AtletaID','Rodada', 'Jogos', 'Scouts', 'Pontos'],inplace=True)

Colunas:
 Index(['ClubeID', 'AtletaID', 'Jogos', 'PontosMedia', 'Pontos', 'Preco', 'A',
       'CA', 'CV', 'DD', 'DP', 'FC', 'FD', 'FF', 'FS', 'FT', 'G', 'GC', 'GS',
       'I', 'PE', 'PP', 'RB', 'SG', 'PrecoVariacao', 'Rodada'],
      dtype='object')

Base:
    ClubeID  AtletaID  Jogos  PontosMedia  Pontos  Preco    A   CA  CV    DD  \
0      276     38055     16         5.89     0.0  28.20  NaN  1.0 NaN  19.0
1      275     36612     18         6.50    15.6  27.43  3.0  NaN NaN   NaN
2      284     86759     21         5.71     3.4  27.21  4.0  3.0 NaN   NaN
3      292     68911     24         3.51     0.7  25.77  5.0  5.0 NaN   NaN
4      262     75295      9         6.32     0.0  23.80  2.0  3.0 NaN   NaN

    DP    FC    FD    FF    FS   FT    G  GC    GS     I     PE  PP    RB  \
0  1.0   NaN   NaN   NaN   1.0  NaN  3.0 NaN  14.0   NaN   15.0 NaN   NaN
1  NaN   7.0   6.0   8.0  23.0  NaN  2.0 NaN   NaN   NaN   26.0 NaN  26.0
2  NaN  30.0  16.0  18.0  75.0  2.0  5.0 NaN   NaN  12.0   62.0 NaN  19.0
3  NaN  33.0  10.0  15.0  33.0  NaN  6.0 NaN   1.0   6.0  101.0 NaN  21.0
4  NaN  17.0  13.0  14.0  23.0  1.0  3.0 NaN   NaN  10.0   13.0 NaN   5.0

    SG  PrecoVariacao  Rodada
0  8.0           0.00      26
1  6.0           2.45      26
2  NaN          -0.73      26
3  NaN          -0.19      26
4  NaN           0.00      26

Tamanaho da base:
  (842, 26)

Quantidade de duplicados:
 False    842
dtype: int64

Quantidade de Atletas Missing:
 0

Quantidade de clubes Missing:
 0

Quantidade de jogadores por rodada:  26    842
Name: Rodada, dtype: int64
RODADA 0 É ANTES DO GAME COMEÇAR, JOGADORES COM PONTOS ZERADO E VALOR INICIAL

In [44]:
print('Tamanho da base de 2018 antes da limpeza', rodada_26.shape)
rodada_26['Ano'] = 2015
# Eliminando jogadores com nan no nome do clube e que não participaram de jogos
rodada_26 = rodada_26[rodada_26.Scouts>0]
rodada_26 = rodada_26[(rodada_26.PrecoVariacao != 0) | (rodada_26.Pontos!=0)]
rodada_26.drop_duplicates(subset=['AtletaID','ClubeID','Rodada'],keep='last', inplace=True)
print('Tamanho da base com apenas jogadores que jogaram:',rodada_26.shape)
rodada_26_limpo = rodada_26[(~rodada_26.ClubeID.isnull()) & (rodada_26.Rodada>0)]
print('Tamanho da base limpa:', rodada_26_limpo.shape)

rodada_26_limpo.sample(10)

Tamanho da base de 2018 antes da limpeza (842, 27)
Tamanho da base com apenas jogadores que jogaram: (280, 28)
Tamanho da base limpa: (280, 28)

,ClubeID,AtletaID,Jogos,PontosMedia,Pontos,Preco,A,CA,CV,DD,DP,FC,FD,FF,FS,FT,G,GC,GS,I,PE,PP,RB,SG,PrecoVariacao,Rodada,Scouts,Ano
523,276,87486,7,3.78,-1.6,2.04,1.0,1.0,NaN,NaN,NaN,9.0,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,4.0,4.0,-1.04,26,31.0,2015
134,275,71549,11,2.10,0.6,6.42,3.0,3.0,NaN,NaN,NaN,13.0,7.0,4.0,12.0,NaN,NaN,NaN,NaN,NaN,24.0,NaN,7.0,NaN,-0.18,26,73.0,2015
40,315,68698,22,1.24,0.9,8.53,NaN,8.0,NaN,NaN,NaN,35.0,5.0,5.0,13.0,NaN,1.0,NaN,NaN,5.0,63.0,NaN,35.0,NaN,0.54,26,170.0,2015
312,314,89696,20,2.62,5.0,4.12,NaN,3.0,NaN,NaN,NaN,15.0,8.0,14.0,24.0,1.0,2.0,NaN,NaN,1.0,23.0,NaN,14.0,NaN,0.51,26,105.0,2015
29,314,60822,12,1.66,3.1,8.83,1.0,NaN,NaN,NaN,NaN,6.0,1.0,10.0,7.0,NaN,NaN,NaN,NaN,3.0,36.0,NaN,11.0,NaN,0.22,26,75.0,2015
780,315,51042,23,4.02,1.3,11.22,NaN,2.0,1.0,NaN,NaN,24.0,10.0,8.0,40.0,NaN,2.0,NaN,NaN,5.0,83.0,NaN,29.0,8.0,-0.29,26,212.0,2015
440,292,74140,13,3.05,0.0,15.74,NaN,NaN,NaN,NaN,NaN,3.0,5.0,2.0,20.0,NaN,2.0,NaN,NaN,1.0,26.0,NaN,10.0,NaN,-1.01,26,69.0,2015
138,282,79826,18,2.48,-0.8,6.38,2.0,4.0,NaN,NaN,NaN,26.0,2.0,9.0,9.0,NaN,NaN,NaN,NaN,1.0,58.0,NaN,15.0,7.0,0.02,26,133.0,2015
16,275,38957,23,4.45,12.7,19.46,4.0,NaN,NaN,NaN,NaN,19.0,11.0,15.0,36.0,NaN,6.0,NaN,NaN,8.0,85.0,NaN,20.0,NaN,2.51,26,204.0,2015
45,283,69014,24,2.74,-0.6,8.46,NaN,2.0,NaN,NaN,NaN,23.0,2.0,10.0,19.0,NaN,1.0,NaN,NaN,NaN,59.0,NaN,28.0,5.0,-0.23,26,149.0,2015

In [45]:
scouts_2015 = pd.read_csv('D:\\Dropbox\\Projeto Brasileirao\\caRtola\\data\\2015\\2015_scouts_raw.csv')

In [46]:
scouts_2015 = scouts_2015.append(rodada_38_limpo)
scouts_2015 = scouts_2015.append(rodada_26_limpo)
scouts_2015.sort_values(by=['AtletaID','Rodada', 'Jogos', 'Scouts', 'Pontos'],inplace=True)

In [47]:
#scouts_2015.to_csv('D:\\Dropbox\\Projeto Brasileirao\\caRtola\\data\\2015\\2015_scouts_raw.csv',index=False)